"""Add unread_count to Donation model

Revision ID: 096d80c0bf01
Revises: a55171edb792
Create Date: 2024-12-18 00:15:17.454785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096d80c0bf01'
down_revision = 'a55171edb792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_count', sa.Integer(), nullable=True))
        batch_op.drop_column('is_unavailable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unavailable', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('unread_count')

    # ### end Alembic commands ###
