"""Added reward points for donors and donation tables

Revision ID: 20f3bd2fef0f
Revises: 33419ffe5beb
Create Date: 2024-12-15 23:38:01.381371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f3bd2fef0f'
down_revision = '33419ffe5beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_column('users', 'points')

    # ### end Alembic commands ###
