"""Add reward_points column to users table

Revision ID: 33419ffe5beb
Revises: 92dcfcec18a1
Create Date: 2024-12-15 20:29:27.833364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33419ffe5beb'
down_revision = '92dcfcec18a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
