"""Add purchased column to Donation model

Revision ID: 40859cac8d47
Revises: 9adb7e216304
Create Date: 2024-12-18 11:53:10.017864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40859cac8d47'
down_revision = '9adb7e216304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('unread')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
