"""Added buyer_email to Donation model

Revision ID: 4721e14d4e3b
Revises: 153c6322bdb3
Create Date: 2024-12-17 22:42:38.285960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4721e14d4e3b'
down_revision = '153c6322bdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('buyer_email')

    # ### end Alembic commands ###
