"""Add points column to users table

Revision ID: 6184da636c13
Revises: dfe187c748fa
Create Date: 2024-12-15 23:56:28.219063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6184da636c13'
down_revision = 'dfe187c748fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('reward_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
