"""Add status column into Donation model

Revision ID: 80b13aadf3d4
Revises: 4721e14d4e3b
Create Date: 2024-12-17 23:46:29.499757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b13aadf3d4'
down_revision = '4721e14d4e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('buyer_email')
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('buyer_email', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
