"""Add unread column to chat table

Revision ID: 9adb7e216304
Revises: 2bc90936e2d9
Create Date: 2024-12-18 00:40:53.975054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adb7e216304'
down_revision = '2bc90936e2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_read')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('unread_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('unread')

    # ### end Alembic commands ###
