"""Fix for duplicate unique_code column

Revision ID: bd0fdd0a6a3b
Revises: b2bd5d8facfd
Create Date: 2024-12-07 16:08:32.464027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0fdd0a6a3b'
down_revision = 'b2bd5d8facfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kids', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('unique_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('item_type')
        batch_op.drop_column('kids')
        batch_op.drop_column('size')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
