"""Add donated column

Revision ID: df7f71503e8a
Revises: 003760f8690d
Create Date: 2024-12-03 15:18:40.912861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7f71503e8a'
down_revision = '003760f8690d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('notification')
    op.drop_table('_alembic_tmp_donation')
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donated', sa.Boolean(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('donated')

    op.create_table('_alembic_tmp_donation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('donor_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('donated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
