"""Added reward points column to donation table

Revision ID: dfe187c748fa
Revises: 20f3bd2fef0f
Create Date: 2024-12-15 23:45:57.536044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe187c748fa'
down_revision = '20f3bd2fef0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('reward_points')

    # ### end Alembic commands ###
